name = "MerryMagic&Create"
author = "MrPotato82"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "45608a70cefc636dfd388dea0543dcd01602e9c3195c6bb3a7ff96f3b752ceae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
