name = "MerryMagic&Create"
author = "MrPotato82"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b93583e6750f8107ff95208cf677c836a79d8810f4ce2f034850d21cc860b21"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21.1"]
