name = "MerryMagic&Create"
author = "MrPotato82"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6077aa0c9fcc524c31114993c19d1470e217d67b233ca6d53d1958984d0bcb02"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"
