name = "MerryMagic&Create"
author = "MrPotato82"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a782e2c431dd99045b8dcf2584053bb60789eb4c6a44cd54d97c4db2157ac78b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.217"

[options]
acceptable-game-versions = ["1.21.1"]
